# Generated by Django 3.2.8 on 2023-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_type_users_user_hopital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_etablissement', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
