# Generated by Django 3.2.8 on 2023-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_hopital',
            name='etat',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
