# Generated by Django 3.2.8 on 2023-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_user_hopital_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_utili',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_user/'),
        ),
        migrations.AlterField(
            model_name='user_hopital',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_user_h/'),
        ),
    ]
