# Generated by Django 3.2.8 on 2023-04-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_photo_user_hopital_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hopital', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_hopital', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('email_hopital', models.CharField(blank=True, max_length=70, null=True)),
                ('communes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commune', to='admin_app.commune')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tab_user', to='admin_app.user_hopital')),
            ],
        ),
    ]
